name: 'mongodb-cluster'

services:
  mongo1:
    container_name: mongo1
    image: bitnami/mongodb:7.0.14
    volumes:
      - mongodb1:/bitnami/mongodb
      - ./config/mongo1.conf:/opt/bitnami/mongodb/conf/mongodb.conf
      - ./config/mongodb-keyfile:/opt/bitnami/mongodb/keyfile
      - mongologs:/opt/bitnami/mongodb/logs
    networks:
      - mongodb_network
    ports:
      - "27017:27017"
    restart: always

  mongo2:
    container_name: mongo2
    image: bitnami/mongodb:7.0.14
    volumes:
      - mongodb2:/bitnami/mongodb
      - ./config/mongo2.conf:/opt/bitnami/mongodb/conf/mongodb.conf
      - ./config/mongodb-keyfile:/opt/bitnami/mongodb/keyfile
      - mongologs:/opt/bitnami/mongodb/logs
    networks:
      - mongodb_network
    ports:
      - "27018:27017"
    restart: always
    depends_on:
      - mongo1

  mongo3:
    container_name: mongo3
    image: bitnami/mongodb:7.0.14
    volumes:
      - mongodb3:/bitnami/mongodb
      - ./config/mongo3.conf:/opt/bitnami/mongodb/conf/mongodb.conf
      - ./config/mongodb-keyfile:/opt/bitnami/mongodb/keyfile
      - mongologs:/opt/bitnami/mongodb/logs
    networks:
      - mongodb_network
    ports:
      - "27019:27017"
    restart: always
    depends_on:
      - mongo1

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge

volumes:
  mongodb1:
    name: mongodb1
    driver: local
  mongodb2:
    name: mongodb2
    driver: local
  mongodb3:
    name: mongodb3
    driver: local
  mongologs:
    name: mongologs
    driver: local

